# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: postgresql
  encoding: unicode
  timeout: 5000
  pool: 5

development:
  <<: *default
  database: viralcents_development
  pool: 25

test:
  <<: *default
  database: viralcents_test
  pool: 25

production:
  <<: *default
  database: viralcents_production
  endpoint: viralcents-db.cua4w9s0j1kv.ap-southeast-1.rds.amazonaws.com
  port: 5432
  pool: 25
  username: techritzy_viral
  password: viral12345
