# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: postgresql
  encoding: unicode
  timeout: 5000
  pool: 5

development:
  <<: *default
  database: viralcents_development
  
test:
  <<: *default
  database: viralcents_test

production:
  <<: *default
  database: viralcents_production
  username: 
  password: 
